#!/bin/bash
#kasutaja lisamsie skript, mis kontrollib, et skripti käivitav kasutaja on root

kaivitav_kasutaja=$(whoami)
if [ $kaivitav_kasutaja = "root" ]; then

        if [ $# -ne 1 ]; then
        echo "Kasutajajuhend: $0 kasutajad"
        else
                kasutajad=$1
                if [ -f $kasutajad -a -r $kasutajad ]; then
                echo "failid on korras"
                for rida in $(paste -d: $kasutajad $paroolid)
                do
                        kasutajanimi=$(echo "$rida")
                        sh lisa_kasutaja $kasutajanimi
                        parool=$(pwgen -s 8 -1)
                        echo "$kasutajanimi:$parool" | chpasswd
                        echo "$kasutajanimi - $parool" >> loodud_kasutajad_paroolidega
                done
         else
         echo "probleem failiga $failinimi"
         fi
         fi
else
         echo "Sul ei ole õigust antud skripti käivitamiseks"
fi
