#!/bin/bash
#phpmyadmin paigaldusskript
PMA=$(dpkg-query -W -f='{Status}' phpmyadmin 2>/dev/null | grep -c 'ok installed')
if [ $PMA -eq 0 ]; then
        echo "Paigaldame PHPmyadmin ja vajalikud lisad"
        apt install phpmyadmin
        echo "PHPmyadmin on paigaldatud"
elif [ $PMA -eq 1 ]; then
        echo "PHPmyadmin on juba paigaldatud"
fi
